import os
from datetime import timedelta


class Config:
    APP_ENV = os.getenv("APP_ENV", "development")
    APP_RELEASE = os.getenv("APP_RELEASE")
    LOG_FORMAT = os.getenv(
        "LOG_FORMAT", "json" if APP_ENV == "production" else "text"
    ).lower()
    SECRET_KEY = os.getenv("SECRET_KEY", "development-only-change-me")
    SQLALCHEMY_DATABASE_URI = os.getenv(
        "DATABASE_URL",
        "postgresql+psycopg://gabflow:gabflow@localhost:5432/gabflow",
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ENGINE_OPTIONS = {"pool_pre_ping": True}
    DB_ENFORCE_RUNTIME_ROLE = os.getenv("DB_ENFORCE_RUNTIME_ROLE", "true").lower() == "true"

    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", SECRET_KEY)
    JWT_TOKEN_LOCATION = ["cookies"]
    JWT_COOKIE_SECURE = os.getenv("COOKIE_SECURE", "false").lower() == "true"
    JWT_COOKIE_SAMESITE = "Strict"
    JWT_COOKIE_CSRF_PROTECT = True
    JWT_ACCESS_TOKEN_EXPIRES = timedelta(minutes=int(os.getenv("JWT_ACCESS_TOKEN_MINUTES", "30")))

    RATELIMIT_STORAGE_URI = os.getenv("RATELIMIT_STORAGE_URI", "memory://")
    RATELIMIT_HEADERS_ENABLED = True

    SENTRY_DSN = os.getenv("SENTRY_DSN")
    SENTRY_TRACES_SAMPLE_RATE = float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1"))
    ATTACHMENT_STORAGE_PATH = os.getenv("ATTACHMENT_STORAGE_PATH", "/data/attachments")
    STORAGE_ENCRYPTION_MASTER_KEY = os.getenv(
        "STORAGE_ENCRYPTION_MASTER_KEY", SECRET_KEY
    )
    STORAGE_ENCRYPTION_KEY_VERSION = int(
        os.getenv("STORAGE_ENCRYPTION_KEY_VERSION", "1")
    )
    MAX_ATTACHMENT_BYTES = int(os.getenv("MAX_ATTACHMENT_BYTES", str(15 * 1024 * 1024)))
    ATTACHMENT_TOKEN_MAX_AGE = int(os.getenv("ATTACHMENT_TOKEN_MAX_AGE", "300"))
    MALWARE_SCANNER_ENABLED = (
        os.getenv("MALWARE_SCANNER_ENABLED", "true").lower() == "true"
    )
    MALWARE_SCANNER_REQUIRED = (
        os.getenv("MALWARE_SCANNER_REQUIRED", "true").lower() == "true"
    )
    MALWARE_SCANNER_PROVIDER = os.getenv("MALWARE_SCANNER_PROVIDER", "clamd")
    MALWARE_SCANNER_HOST = os.getenv("MALWARE_SCANNER_HOST", "clamav")
    MALWARE_SCANNER_PORT = int(os.getenv("MALWARE_SCANNER_PORT", "3310"))
    MALWARE_SCANNER_TIMEOUT_SECONDS = float(
        os.getenv("MALWARE_SCANNER_TIMEOUT_SECONDS", "30")
    )
    MALWARE_SCANNER_MAX_BYTES = int(
        os.getenv("MALWARE_SCANNER_MAX_BYTES", str(30 * 1024 * 1024))
    )
    MALWARE_SCANNER_CHUNK_BYTES = int(
        os.getenv("MALWARE_SCANNER_CHUNK_BYTES", "65536")
    )
    RAG_STORAGE_PATH = os.getenv("RAG_STORAGE_PATH", "/data/rag")
    RAG_MAX_DOCUMENT_BYTES = int(os.getenv("RAG_MAX_DOCUMENT_BYTES", "26214400"))
    RAG_DOWNLOAD_TOKEN_MAX_AGE = int(os.getenv("RAG_DOWNLOAD_TOKEN_MAX_AGE", "300"))
    RAG_ALLOW_LEGACY_STORAGE_KEYS = (
        os.getenv("RAG_ALLOW_LEGACY_STORAGE_KEYS", "true").lower() == "true"
    )
    RAG_EMBEDDING_PROVIDER = os.getenv("RAG_EMBEDDING_PROVIDER", "ollama")
    RAG_INGESTION_TIMEOUT_SECONDS = int(
        os.getenv("RAG_INGESTION_TIMEOUT_SECONDS", "120")
    )
    RAG_CHUNK_SIZE_CHARS = int(os.getenv("RAG_CHUNK_SIZE_CHARS", "1200"))
    RAG_CHUNK_OVERLAP_CHARS = int(os.getenv("RAG_CHUNK_OVERLAP_CHARS", "150"))
    RAG_MIN_TEXT_CHARS = int(os.getenv("RAG_MIN_TEXT_CHARS", "20"))
    RAG_OPERATIONAL_MEMORY_ENABLED = (
        os.getenv("RAG_OPERATIONAL_MEMORY_ENABLED", "true").lower() == "true"
    )
    RAG_RETRIEVAL_MAX_RESULTS = int(os.getenv("RAG_RETRIEVAL_MAX_RESULTS", "5"))
    RAG_RETRIEVAL_CANDIDATE_LIMIT = int(os.getenv("RAG_RETRIEVAL_CANDIDATE_LIMIT", "200"))
    RAG_RETRIEVAL_SCAN_BATCH_SIZE = int(os.getenv("RAG_RETRIEVAL_SCAN_BATCH_SIZE", "500"))
    RAG_HYBRID_DATABASE_ENABLED = (
        os.getenv("RAG_HYBRID_DATABASE_ENABLED", "true").lower() == "true"
    )
    RAG_HYBRID_RRF_K = int(os.getenv("RAG_HYBRID_RRF_K", "60"))
    RAG_HYBRID_HNSW_EF_SEARCH = int(
        os.getenv("RAG_HYBRID_HNSW_EF_SEARCH", "100")
    )
    RAG_QUERY_EXPANSION_MAX_QUERIES = int(
        os.getenv("RAG_QUERY_EXPANSION_MAX_QUERIES", "3")
    )
    RAG_RETRIEVAL_MAX_CHUNKS_PER_DOCUMENT = int(
        os.getenv("RAG_RETRIEVAL_MAX_CHUNKS_PER_DOCUMENT", "2")
    )
    RAG_RETRIEVAL_SCORE_THRESHOLD = float(os.getenv("RAG_RETRIEVAL_SCORE_THRESHOLD", "0.28"))
    RAG_RETRIEVAL_MIN_EVIDENCE_SCORE = float(
        os.getenv("RAG_RETRIEVAL_MIN_EVIDENCE_SCORE", "0.42")
    )
    RAG_RETRIEVAL_AUTHORITY_RERANK_WEIGHT = float(
        os.getenv("RAG_RETRIEVAL_AUTHORITY_RERANK_WEIGHT", "0.03")
    )
    RAG_RETRIEVAL_FRESHNESS_RERANK_WEIGHT = float(
        os.getenv("RAG_RETRIEVAL_FRESHNESS_RERANK_WEIGHT", "0.01")
    )
    RAG_NEURAL_RERANK_ENABLED = (
        os.getenv("RAG_NEURAL_RERANK_ENABLED", "true").lower() == "true"
    )
    RAG_NEURAL_RERANK_PROVIDER = os.getenv(
        "RAG_NEURAL_RERANK_PROVIDER", "ollama"
    )
    RAG_NEURAL_RERANK_MODEL = os.getenv(
        "RAG_NEURAL_RERANK_MODEL", os.getenv("AI_TRIAGE_MODEL", "qwen2.5:3b")
    )
    RAG_NEURAL_RERANK_PROMPT_VERSION = os.getenv(
        "RAG_NEURAL_RERANK_PROMPT_VERSION", "rag-neural-rerank-v1"
    )
    RAG_NEURAL_RERANK_TIMEOUT_SECONDS = int(
        os.getenv("RAG_NEURAL_RERANK_TIMEOUT_SECONDS", "8")
    )
    RAG_NEURAL_RERANK_CANDIDATE_LIMIT = int(
        os.getenv("RAG_NEURAL_RERANK_CANDIDATE_LIMIT", "12")
    )
    RAG_NEURAL_RERANK_CONTENT_CHARS = int(
        os.getenv("RAG_NEURAL_RERANK_CONTENT_CHARS", "700")
    )
    RAG_NEURAL_RERANK_WEIGHT = float(
        os.getenv("RAG_NEURAL_RERANK_WEIGHT", "0.55")
    )
    RAG_NEURAL_RERANK_MIN_SCORE = float(
        os.getenv("RAG_NEURAL_RERANK_MIN_SCORE", "0.20")
    )
    RAG_NEURAL_RERANK_FALLBACK_ENABLED = (
        os.getenv("RAG_NEURAL_RERANK_FALLBACK_ENABLED", "true").lower() == "true"
    )
    RAG_NEURAL_RERANK_ADAPTIVE_ENABLED = (
        os.getenv("RAG_NEURAL_RERANK_ADAPTIVE_ENABLED", "true").lower() == "true"
    )
    RAG_NEURAL_RERANK_SKIP_MIN_SCORE = float(
        os.getenv("RAG_NEURAL_RERANK_SKIP_MIN_SCORE", "0.70")
    )
    RAG_NEURAL_RERANK_SKIP_MIN_MARGIN = float(
        os.getenv("RAG_NEURAL_RERANK_SKIP_MIN_MARGIN", "0.10")
    )
    RAG_NEURAL_RERANK_MAX_TOKENS = int(
        os.getenv("RAG_NEURAL_RERANK_MAX_TOKENS", "384")
    )
    RAG_CONTENT_SECURITY_POLICY_VERSION = os.getenv(
        "RAG_CONTENT_SECURITY_POLICY_VERSION",
        "rag-content-security-v2",
    )
    RAG_CONTENT_SECURITY_DETECTOR_VERSION = os.getenv(
        "RAG_CONTENT_SECURITY_DETECTOR_VERSION",
        "canonical-deterministic-v2",
    )
    RAG_CONTENT_SECURITY_MAX_CANONICAL_CHARS = int(
        os.getenv("RAG_CONTENT_SECURITY_MAX_CANONICAL_CHARS", "1000000")
    )
    RAG_CONTENT_SECURITY_MAX_DECODED_CHARS = int(
        os.getenv("RAG_CONTENT_SECURITY_MAX_DECODED_CHARS", "4096")
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_ENABLED = (
        os.getenv("RAG_PROMPT_INJECTION_CLASSIFIER_ENABLED", "true").lower() == "true"
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_REQUIRED = (
        os.getenv("RAG_PROMPT_INJECTION_CLASSIFIER_REQUIRED", "true").lower() == "true"
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_PROVIDER = os.getenv(
        "RAG_PROMPT_INJECTION_CLASSIFIER_PROVIDER", "ollama"
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_BASE_URL = os.getenv(
        "RAG_PROMPT_INJECTION_CLASSIFIER_BASE_URL",
        os.getenv("OLLAMA_BASE_URL", "http://ollama:11434"),
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_MODEL = os.getenv(
        "RAG_PROMPT_INJECTION_CLASSIFIER_MODEL", "qwen2.5:1.5b"
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_VERSION = os.getenv(
        "RAG_PROMPT_INJECTION_CLASSIFIER_VERSION", "prompt-injection-classifier-v1"
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_TIMEOUT_SECONDS = int(
        os.getenv("RAG_PROMPT_INJECTION_CLASSIFIER_TIMEOUT_SECONDS", "12")
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_MAX_CHARS = int(
        os.getenv("RAG_PROMPT_INJECTION_CLASSIFIER_MAX_CHARS", "16000")
    )
    RAG_PROMPT_INJECTION_CLASSIFIER_MAX_TOKENS = int(
        os.getenv("RAG_PROMPT_INJECTION_CLASSIFIER_MAX_TOKENS", "256")
    )
    RAG_PROMPT_INJECTION_REQUIRE_DISTINCT_MODEL = (
        os.getenv("RAG_PROMPT_INJECTION_REQUIRE_DISTINCT_MODEL", "true").lower()
        == "true"
    )
    RAG_PROMPT_INJECTION_FAIL_CLOSED = (
        os.getenv("RAG_PROMPT_INJECTION_FAIL_CLOSED", "true").lower() == "true"
    )
    RAG_OUTPUT_VALIDATION_POLICY_VERSION = os.getenv(
        "RAG_OUTPUT_VALIDATION_POLICY_VERSION", "rag-output-security-v1"
    )
    RAG_OUTPUT_VALIDATOR_VERSION = os.getenv(
        "RAG_OUTPUT_VALIDATOR_VERSION", "deterministic-output-validator-v1"
    )
    RAG_OUTPUT_ROLLOUT_STAGES = [
        int(value)
        for value in os.getenv("RAG_OUTPUT_ROLLOUT_STAGES", "5,20,50,100").split(",")
        if value.strip()
    ]
    RAG_OUTPUT_ROLLOUT_MIN_SAMPLES = int(
        os.getenv("RAG_OUTPUT_ROLLOUT_MIN_SAMPLES", "20")
    )
    RAG_OUTPUT_ROLLOUT_MAX_BLOCK_RATE = float(
        os.getenv("RAG_OUTPUT_ROLLOUT_MAX_BLOCK_RATE", "0.10")
    )
    RAG_ANSWER_GENERATION_ENABLED = (
        os.getenv("RAG_ANSWER_GENERATION_ENABLED", "true").lower() == "true"
    )
    RAG_ANSWER_PROVIDER = os.getenv("RAG_ANSWER_PROVIDER", "ollama")
    RAG_ANSWER_MODEL = os.getenv(
        "RAG_ANSWER_MODEL", os.getenv("AI_TRIAGE_MODEL", "qwen2.5:3b")
    )
    RAG_ANSWER_PROMPT_VERSION = os.getenv(
        "RAG_ANSWER_PROMPT_VERSION", "rag-grounded-answer-v1"
    )
    RAG_ANSWER_TIMEOUT_SECONDS = int(
        os.getenv("RAG_ANSWER_TIMEOUT_SECONDS", "20")
    )
    RAG_ANSWER_MAX_SOURCES = int(os.getenv("RAG_ANSWER_MAX_SOURCES", "3"))
    RAG_ANSWER_SOURCE_CHARS = int(os.getenv("RAG_ANSWER_SOURCE_CHARS", "900"))
    RAG_ANSWER_MAX_CLAIMS = int(os.getenv("RAG_ANSWER_MAX_CLAIMS", "5"))
    RAG_ANSWER_MAX_CHARS = int(os.getenv("RAG_ANSWER_MAX_CHARS", "5000"))
    RAG_ANSWER_MAX_TOKENS = int(os.getenv("RAG_ANSWER_MAX_TOKENS", "512"))
    RAG_ANSWER_CITATION_SUPPORT_THRESHOLD = float(
        os.getenv("RAG_ANSWER_CITATION_SUPPORT_THRESHOLD", "0.18")
    )
    RAG_ANSWER_FALLBACK_REFUSAL_ENABLED = (
        os.getenv("RAG_ANSWER_FALLBACK_REFUSAL_ENABLED", "true").lower() == "true"
    )
    RAG_ENTAILMENT_ENABLED = (
        os.getenv("RAG_ENTAILMENT_ENABLED", "true").lower() == "true"
    )
    RAG_ENTAILMENT_PROVIDER = os.getenv("RAG_ENTAILMENT_PROVIDER", "ollama")
    RAG_ENTAILMENT_MODEL = os.getenv(
        "RAG_ENTAILMENT_MODEL", os.getenv("AI_TRIAGE_MODEL", "qwen2.5:3b")
    )
    RAG_ENTAILMENT_PROMPT_VERSION = os.getenv(
        "RAG_ENTAILMENT_PROMPT_VERSION", "rag-entailment-v1"
    )
    RAG_ENTAILMENT_TIMEOUT_SECONDS = int(
        os.getenv("RAG_ENTAILMENT_TIMEOUT_SECONDS", "45")
    )
    RAG_ENTAILMENT_MIN_SCORE = float(
        os.getenv("RAG_ENTAILMENT_MIN_SCORE", "0.72")
    )
    RAG_ENTAILMENT_FAIL_CLOSED = (
        os.getenv("RAG_ENTAILMENT_FAIL_CLOSED", "true").lower() == "true"
    )
    RAG_NLI_ENABLED = os.getenv("RAG_NLI_ENABLED", "true").lower() == "true"
    RAG_NLI_PROVIDER = os.getenv("RAG_NLI_PROVIDER", "ollama")
    RAG_NLI_BASE_URL = os.getenv("RAG_NLI_BASE_URL", os.getenv("OLLAMA_BASE_URL", "http://ollama:11434"))
    RAG_NLI_MODEL = os.getenv("RAG_NLI_MODEL", "qwen2.5:0.5b")
    RAG_NLI_PROMPT_VERSION = os.getenv("RAG_NLI_PROMPT_VERSION", "rag-nli-v2")
    RAG_NLI_TIMEOUT_SECONDS = int(os.getenv("RAG_NLI_TIMEOUT_SECONDS", "12"))
    RAG_NLI_MIN_SCORE = float(
        os.getenv("RAG_NLI_MIN_SCORE", os.getenv("RAG_ENTAILMENT_MIN_SCORE", "0.72"))
    )
    RAG_NLI_FAIL_CLOSED = (
        os.getenv("RAG_NLI_FAIL_CLOSED", "true").lower() == "true"
    )
    RAG_NLI_REQUIRE_DISTINCT_MODEL = (
        os.getenv("RAG_NLI_REQUIRE_DISTINCT_MODEL", "true").lower() == "true"
    )
    RAG_NLI_MAX_EVIDENCE_CHARS = int(
        os.getenv("RAG_NLI_MAX_EVIDENCE_CHARS", "2400")
    )
    RAG_NLI_MAX_TOKENS = int(os.getenv("RAG_NLI_MAX_TOKENS", "256"))
    RAG_QUERY_LATENCY_BUDGET_MS = int(
        os.getenv("RAG_QUERY_LATENCY_BUDGET_MS", "30000")
    )
    RAG_LEARNING_MIN_SIGNALS = int(os.getenv("RAG_LEARNING_MIN_SIGNALS", "3"))
    RAG_LEARNING_MAX_ADJUSTMENT = float(
        os.getenv("RAG_LEARNING_MAX_ADJUSTMENT", "0.12")
    )
    RAG_LEARNING_DECAY_HALF_LIFE_DAYS = int(
        os.getenv("RAG_LEARNING_DECAY_HALF_LIFE_DAYS", "90")
    )
    RAG_LEARNING_MAX_EXAMPLES = int(
        os.getenv("RAG_LEARNING_MAX_EXAMPLES", "200")
    )
    RAG_LEARNING_EVALUATION_K = int(os.getenv("RAG_LEARNING_EVALUATION_K", "5"))
    RAG_LEARNING_MAX_REGRESSION = float(
        os.getenv("RAG_LEARNING_MAX_REGRESSION", "0.05")
    )
    RAG_LEARNING_CANARY_PERCENT = int(
        os.getenv("RAG_LEARNING_CANARY_PERCENT", "10")
    )
    RAG_LEARNING_ONLINE_MIN_SAMPLES = int(
        os.getenv("RAG_LEARNING_ONLINE_MIN_SAMPLES", "10")
    )
    RAG_LEARNING_ONLINE_MAX_NEGATIVE_RATE = float(
        os.getenv("RAG_LEARNING_ONLINE_MAX_NEGATIVE_RATE", "0.60")
    )
    RAG_QUALITY_ONLINE_MIN_SAMPLES = int(
        os.getenv("RAG_QUALITY_ONLINE_MIN_SAMPLES", "20")
    )
    RAG_QUALITY_ONLINE_MAX_FALLBACK_RATE = float(
        os.getenv("RAG_QUALITY_ONLINE_MAX_FALLBACK_RATE", "0.20")
    )
    RAG_QUALITY_ONLINE_MAX_SEMANTIC_REJECTION_RATE = float(
        os.getenv("RAG_QUALITY_ONLINE_MAX_SEMANTIC_REJECTION_RATE", "0.30")
    )
    RAG_QUALITY_ONLINE_MAX_REFUSAL_RATE = float(
        os.getenv("RAG_QUALITY_ONLINE_MAX_REFUSAL_RATE", "0.50")
    )
    RAG_QUALITY_ONLINE_MAX_LATENCY_BUDGET_RATE = float(
        os.getenv("RAG_QUALITY_ONLINE_MAX_LATENCY_BUDGET_RATE", "0.10")
    )
    RAG_QUALITY_ROLLOUT_STAGES = os.getenv(
        "RAG_QUALITY_ROLLOUT_STAGES", "5,20,50,100"
    )
    RAG_QUALITY_ROLLOUT_MIN_SAMPLES = int(
        os.getenv("RAG_QUALITY_ROLLOUT_MIN_SAMPLES", "20")
    )
    RAG_QUALITY_ROLLOUT_MIN_WINDOW_SECONDS = int(
        os.getenv("RAG_QUALITY_ROLLOUT_MIN_WINDOW_SECONDS", "3600")
    )
    RAG_QUALITY_ROLLOUT_CHECK_INTERVAL_SECONDS = int(
        os.getenv("RAG_QUALITY_ROLLOUT_CHECK_INTERVAL_SECONDS", "300")
    )
    RAG_QUALITY_ROLLOUT_MAX_RATE_REGRESSION = float(
        os.getenv("RAG_QUALITY_ROLLOUT_MAX_RATE_REGRESSION", "0.05")
    )
    RESEND_API_KEY = os.getenv("RESEND_API_KEY")
    RESEND_FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL")
    RESEND_TIMEOUT_SECONDS = int(os.getenv("RESEND_TIMEOUT_SECONDS", "10"))
    RESEND_WEBHOOK_SECRET = os.getenv("RESEND_WEBHOOK_SECRET")
    RESEND_WEBHOOK_TOLERANCE_SECONDS = int(os.getenv("RESEND_WEBHOOK_TOLERANCE_SECONDS", "300"))
    META_APP_SECRET = os.getenv("META_APP_SECRET")
    META_WEBHOOK_VERIFY_TOKEN = os.getenv("META_WEBHOOK_VERIFY_TOKEN")
    WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.getenv("WHATSAPP_WEBHOOK_VERIFY_TOKEN")
    WORKER_POLL_SECONDS = float(os.getenv("WORKER_POLL_SECONDS", "2"))
    WORKER_BATCH_SIZE = int(os.getenv("WORKER_BATCH_SIZE", "20"))
    WORKER_MAX_ATTEMPTS = int(os.getenv("WORKER_MAX_ATTEMPTS", "5"))
    WORKER_RETRY_BASE_SECONDS = int(os.getenv("WORKER_RETRY_BASE_SECONDS", "30"))
    WORKER_RETRY_MAX_SECONDS = int(os.getenv("WORKER_RETRY_MAX_SECONDS", "3600"))
    WORKER_LOCK_TIMEOUT_SECONDS = int(os.getenv("WORKER_LOCK_TIMEOUT_SECONDS", "300"))
    WORKER_HEARTBEAT_SECONDS = int(os.getenv("WORKER_HEARTBEAT_SECONDS", "60"))
    WORKER_QUEUE = os.getenv("WORKER_QUEUE", "all").lower()
    WORKER_RUN_SCHEDULER = (
        os.getenv("WORKER_RUN_SCHEDULER", "true").lower() == "true"
    )
    SCHEDULER_INTERVAL_SECONDS = int(os.getenv("SCHEDULER_INTERVAL_SECONDS", "30"))
    RAG_SLO_QUERY_P95_MS = int(os.getenv("RAG_SLO_QUERY_P95_MS", "15000"))
    RAG_SLO_QUEUE_MAX_AGE_SECONDS = int(
        os.getenv("RAG_SLO_QUEUE_MAX_AGE_SECONDS", "300")
    )
    RAG_METRICS_WINDOW_HOURS = int(os.getenv("RAG_METRICS_WINDOW_HOURS", "24"))
    RAG_THEMATIC_MIN_GROUP_SIZE = int(
        os.getenv("RAG_THEMATIC_MIN_GROUP_SIZE", "3")
    )
    METRICS_BEARER_TOKEN = os.getenv("METRICS_BEARER_TOKEN")
    AI_TRIAGE_PROVIDER = os.getenv("AI_TRIAGE_PROVIDER", "ollama")
    AI_TRIAGE_MODEL = os.getenv("AI_TRIAGE_MODEL", "qwen2.5:3b")
    AI_TRIAGE_FALLBACK_MODEL = os.getenv(
        "AI_TRIAGE_FALLBACK_MODEL",
        "gabflow-triage-rules-v1",
    )
    AI_TRIAGE_PROMPT_VERSION = os.getenv("AI_TRIAGE_PROMPT_VERSION", "triage-v3")
    AI_TRIAGE_TIMEOUT_SECONDS = int(os.getenv("AI_TRIAGE_TIMEOUT_SECONDS", "120"))
    AI_TRIAGE_FALLBACK_ENABLED = os.getenv(
        "AI_TRIAGE_FALLBACK_ENABLED",
        "true",
    ).lower() == "true"
    AI_ASSISTANCE_PROVIDER = os.getenv("AI_ASSISTANCE_PROVIDER", AI_TRIAGE_PROVIDER)
    AI_ASSISTANCE_MODEL = os.getenv("AI_ASSISTANCE_MODEL", AI_TRIAGE_MODEL)
    AI_ASSISTANCE_FALLBACK_MODEL = os.getenv(
        "AI_ASSISTANCE_FALLBACK_MODEL", "gabflow-assistance-rules-v1"
    )
    AI_ASSISTANCE_PROMPT_VERSION = os.getenv(
        "AI_ASSISTANCE_PROMPT_VERSION", "assistance-v1"
    )
    AI_ASSISTANCE_TIMEOUT_SECONDS = int(
        os.getenv("AI_ASSISTANCE_TIMEOUT_SECONDS", str(AI_TRIAGE_TIMEOUT_SECONDS))
    )
    AI_ASSISTANCE_FALLBACK_ENABLED = os.getenv(
        "AI_ASSISTANCE_FALLBACK_ENABLED", "true"
    ).lower() == "true"
    AI_LEGISLATIVE_PROVIDER = os.getenv("AI_LEGISLATIVE_PROVIDER", AI_TRIAGE_PROVIDER)
    AI_LEGISLATIVE_MODEL = os.getenv("AI_LEGISLATIVE_MODEL", AI_TRIAGE_MODEL)
    AI_LEGISLATIVE_FALLBACK_MODEL = os.getenv(
        "AI_LEGISLATIVE_FALLBACK_MODEL", "gabflow-legislative-rules-v1"
    )
    AI_LEGISLATIVE_PROMPT_VERSION = os.getenv(
        "AI_LEGISLATIVE_PROMPT_VERSION", "legislative-v1"
    )
    AI_LEGISLATIVE_TIMEOUT_SECONDS = int(
        os.getenv("AI_LEGISLATIVE_TIMEOUT_SECONDS", str(AI_TRIAGE_TIMEOUT_SECONDS))
    )
    AI_LEGISLATIVE_FALLBACK_ENABLED = os.getenv(
        "AI_LEGISLATIVE_FALLBACK_ENABLED", "true"
    ).lower() == "true"
    AI_DUPLICATE_PROVIDER = os.getenv("AI_DUPLICATE_PROVIDER", "ollama")
    AI_EMBEDDING_MODEL = os.getenv("AI_EMBEDDING_MODEL", "nomic-embed-text")
    AI_DUPLICATE_WINDOW_DAYS = int(os.getenv("AI_DUPLICATE_WINDOW_DAYS", "180"))
    AI_DUPLICATE_SCORE_THRESHOLD = float(os.getenv("AI_DUPLICATE_SCORE_THRESHOLD", "0.72"))
    AI_DUPLICATE_MAX_SUGGESTIONS = int(os.getenv("AI_DUPLICATE_MAX_SUGGESTIONS", "5"))
    AI_DUPLICATE_CANDIDATE_LIMIT = int(os.getenv("AI_DUPLICATE_CANDIDATE_LIMIT", "100"))
    AI_PRECEDENT_PROVIDER = os.getenv("AI_PRECEDENT_PROVIDER", AI_DUPLICATE_PROVIDER)
    AI_PRECEDENT_SCORE_THRESHOLD = float(
        os.getenv("AI_PRECEDENT_SCORE_THRESHOLD", "0.60")
    )
    AI_PRECEDENT_MAX_RESULTS = int(os.getenv("AI_PRECEDENT_MAX_RESULTS", "10"))
    AI_PRECEDENT_CANDIDATE_LIMIT = int(
        os.getenv("AI_PRECEDENT_CANDIDATE_LIMIT", "200")
    )
    AI_FOUNDATION_PROVIDER = os.getenv("AI_FOUNDATION_PROVIDER", AI_PRECEDENT_PROVIDER)
    AI_FOUNDATION_SCORE_THRESHOLD = float(
        os.getenv("AI_FOUNDATION_SCORE_THRESHOLD", "0.55")
    )
    AI_FOUNDATION_MAX_RESULTS = int(os.getenv("AI_FOUNDATION_MAX_RESULTS", "5"))
    AI_FOUNDATION_CANDIDATE_LIMIT = int(
        os.getenv("AI_FOUNDATION_CANDIDATE_LIMIT", "200")
    )
    AUDIO_TRANSCRIPTION_PROVIDER = os.getenv(
        "AUDIO_TRANSCRIPTION_PROVIDER", "faster-whisper"
    )
    AUDIO_TRANSCRIPTION_MODEL = os.getenv("AUDIO_TRANSCRIPTION_MODEL", "base")
    AUDIO_TRANSCRIPTION_DEVICE = os.getenv("AUDIO_TRANSCRIPTION_DEVICE", "cpu")
    AUDIO_TRANSCRIPTION_COMPUTE_TYPE = os.getenv(
        "AUDIO_TRANSCRIPTION_COMPUTE_TYPE", "int8"
    )
    AUDIO_TRANSCRIPTION_LANGUAGE = os.getenv("AUDIO_TRANSCRIPTION_LANGUAGE", "pt")
    AUDIO_TRANSCRIPTION_CACHE_DIR = os.getenv(
        "AUDIO_TRANSCRIPTION_CACHE_DIR", "/models/whisper"
    )
    AUDIO_TRANSCRIPTION_MAX_DURATION_SECONDS = int(
        os.getenv("AUDIO_TRANSCRIPTION_MAX_DURATION_SECONDS", "900")
    )
    DOCUMENT_OCR_PROVIDER = os.getenv("DOCUMENT_OCR_PROVIDER", "tesseract")
    DOCUMENT_OCR_MODEL = os.getenv("DOCUMENT_OCR_MODEL", "tesseract-5")
    DOCUMENT_OCR_LANGUAGE = os.getenv("DOCUMENT_OCR_LANGUAGE", "por")
    DOCUMENT_OCR_MAX_PAGES = int(os.getenv("DOCUMENT_OCR_MAX_PAGES", "500"))
    DOCUMENT_OCR_MAX_PIXELS = int(os.getenv("DOCUMENT_OCR_MAX_PIXELS", "25000000"))
    DOCUMENT_OCR_NATIVE_MIN_CHARS = int(
        os.getenv("DOCUMENT_OCR_NATIVE_MIN_CHARS", "40")
    )
    DOCUMENT_OCR_BATCH_SIZE = int(os.getenv("DOCUMENT_OCR_BATCH_SIZE", "8"))
    DOCUMENT_PARSER_ISOLATION_ENABLED = (
        os.getenv("DOCUMENT_PARSER_ISOLATION_ENABLED", "true").lower() == "true"
    )
    DOCUMENT_PARSER_SOCKET_PATH = os.getenv(
        "DOCUMENT_PARSER_SOCKET_PATH", "/run/gabflow-parser/parser.sock"
    )
    DOCUMENT_PARSER_TIMEOUT_SECONDS = float(
        os.getenv("DOCUMENT_PARSER_TIMEOUT_SECONDS", "120")
    )
    DOCUMENT_PARSER_MAX_RESPONSE_BYTES = int(
        os.getenv("DOCUMENT_PARSER_MAX_RESPONSE_BYTES", "10485760")
    )
    OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://ollama:11434")


class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = "sqlite+pysqlite:///:memory:"
    SQLALCHEMY_ENGINE_OPTIONS = {
        "execution_options": {"schema_translate_map": {"rag_global": None}}
    }
    JWT_COOKIE_SECURE = False
    RATELIMIT_ENABLED = False
    SENTRY_DSN = None
    RAG_OPERATIONAL_MEMORY_ENABLED = False
    RAG_NEURAL_RERANK_ENABLED = False
    RAG_NEURAL_RERANK_ADAPTIVE_ENABLED = False
    RAG_ANSWER_GENERATION_ENABLED = False
    RAG_ENTAILMENT_ENABLED = False
    RAG_NLI_ENABLED = False
    RAG_PROMPT_INJECTION_CLASSIFIER_ENABLED = False
    RAG_PROMPT_INJECTION_CLASSIFIER_REQUIRED = False
    MALWARE_SCANNER_PROVIDER = "local"
    DOCUMENT_PARSER_ISOLATION_ENABLED = False
    RAG_LEARNING_MIN_SIGNALS = 1
    RAG_LEARNING_ONLINE_MIN_SAMPLES = 2
    RAG_QUALITY_ONLINE_MIN_SAMPLES = 2
    RAG_QUALITY_ROLLOUT_MIN_SAMPLES = 2
    RAG_QUALITY_ROLLOUT_MIN_WINDOW_SECONDS = 0
    RAG_QUALITY_ROLLOUT_CHECK_INTERVAL_SECONDS = 0
    WORKER_HEARTBEAT_SECONDS = 0
    METRICS_BEARER_TOKEN = "test-metrics-token"  # noqa: S105
    WORKER_QUEUE = "all"
    WORKER_RUN_SCHEDULER = True
    RESEND_API_KEY = None
    RESEND_FROM_EMAIL = None
    RESEND_WEBHOOK_SECRET = None
    META_APP_SECRET = None
    META_WEBHOOK_VERIFY_TOKEN = None
    WHATSAPP_WEBHOOK_VERIFY_TOKEN = None
    AI_TRIAGE_PROVIDER = "local"
    AI_TRIAGE_MODEL = "gabflow-triage-rules-v1"
    AI_TRIAGE_FALLBACK_MODEL = "gabflow-triage-rules-v1"
    AI_TRIAGE_PROMPT_VERSION = "triage-v1"
    AI_ASSISTANCE_PROVIDER = "local"
    AI_ASSISTANCE_MODEL = "gabflow-assistance-rules-v1"
    AI_ASSISTANCE_FALLBACK_MODEL = "gabflow-assistance-rules-v1"
    AI_ASSISTANCE_PROMPT_VERSION = "assistance-v1"
    AI_LEGISLATIVE_PROVIDER = "local"
    AI_LEGISLATIVE_MODEL = "gabflow-legislative-rules-v1"
    AI_LEGISLATIVE_FALLBACK_MODEL = "gabflow-legislative-rules-v1"
    AI_LEGISLATIVE_PROMPT_VERSION = "legislative-v1"
    AI_DUPLICATE_PROVIDER = "local"
    AI_PRECEDENT_PROVIDER = "local"
    AI_PRECEDENT_SCORE_THRESHOLD = 0.2
    AI_FOUNDATION_PROVIDER = "local"
    AI_FOUNDATION_SCORE_THRESHOLD = 0.15
    RAG_EMBEDDING_PROVIDER = "local"
