import os
from datetime import timedelta


class Config:
    APP_ENV = os.getenv("APP_ENV", "development")
    APP_RELEASE = os.getenv("APP_RELEASE")
    SECRET_KEY = os.getenv("SECRET_KEY", "development-only-change-me")
    SQLALCHEMY_DATABASE_URI = os.getenv(
        "DATABASE_URL",
        "postgresql+psycopg://gabflow:gabflow@localhost:5432/gabflow",
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ENGINE_OPTIONS = {"pool_pre_ping": True}

    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", SECRET_KEY)
    JWT_TOKEN_LOCATION = ["cookies"]
    JWT_COOKIE_SECURE = os.getenv("COOKIE_SECURE", "false").lower() == "true"
    JWT_COOKIE_SAMESITE = "Strict"
    JWT_COOKIE_CSRF_PROTECT = True
    JWT_ACCESS_TOKEN_EXPIRES = timedelta(minutes=int(os.getenv("JWT_ACCESS_TOKEN_MINUTES", "30")))

    RATELIMIT_STORAGE_URI = os.getenv("RATELIMIT_STORAGE_URI", "memory://")
    RATELIMIT_HEADERS_ENABLED = True

    SENTRY_DSN = os.getenv("SENTRY_DSN")
    SENTRY_TRACES_SAMPLE_RATE = float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1"))
    ATTACHMENT_STORAGE_PATH = os.getenv("ATTACHMENT_STORAGE_PATH", "/data/attachments")
    MAX_ATTACHMENT_BYTES = int(os.getenv("MAX_ATTACHMENT_BYTES", str(15 * 1024 * 1024)))
    ATTACHMENT_TOKEN_MAX_AGE = int(os.getenv("ATTACHMENT_TOKEN_MAX_AGE", "300"))
    RAG_STORAGE_PATH = os.getenv("RAG_STORAGE_PATH", "/data/rag")
    RAG_MAX_DOCUMENT_BYTES = int(os.getenv("RAG_MAX_DOCUMENT_BYTES", "26214400"))
    RAG_EMBEDDING_PROVIDER = os.getenv("RAG_EMBEDDING_PROVIDER", "ollama")
    RAG_INGESTION_TIMEOUT_SECONDS = int(
        os.getenv("RAG_INGESTION_TIMEOUT_SECONDS", "120")
    )
    RAG_CHUNK_SIZE_CHARS = int(os.getenv("RAG_CHUNK_SIZE_CHARS", "1200"))
    RAG_CHUNK_OVERLAP_CHARS = int(os.getenv("RAG_CHUNK_OVERLAP_CHARS", "150"))
    RAG_MIN_TEXT_CHARS = int(os.getenv("RAG_MIN_TEXT_CHARS", "20"))
    RESEND_API_KEY = os.getenv("RESEND_API_KEY")
    RESEND_FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL")
    RESEND_TIMEOUT_SECONDS = int(os.getenv("RESEND_TIMEOUT_SECONDS", "10"))
    WORKER_POLL_SECONDS = float(os.getenv("WORKER_POLL_SECONDS", "2"))
    WORKER_BATCH_SIZE = int(os.getenv("WORKER_BATCH_SIZE", "20"))
    WORKER_MAX_ATTEMPTS = int(os.getenv("WORKER_MAX_ATTEMPTS", "5"))
    WORKER_RETRY_BASE_SECONDS = int(os.getenv("WORKER_RETRY_BASE_SECONDS", "30"))
    WORKER_RETRY_MAX_SECONDS = int(os.getenv("WORKER_RETRY_MAX_SECONDS", "3600"))
    WORKER_LOCK_TIMEOUT_SECONDS = int(os.getenv("WORKER_LOCK_TIMEOUT_SECONDS", "300"))
    SCHEDULER_INTERVAL_SECONDS = int(os.getenv("SCHEDULER_INTERVAL_SECONDS", "30"))
    AI_TRIAGE_PROVIDER = os.getenv("AI_TRIAGE_PROVIDER", "ollama")
    AI_TRIAGE_MODEL = os.getenv("AI_TRIAGE_MODEL", "qwen2.5:3b")
    AI_TRIAGE_FALLBACK_MODEL = os.getenv(
        "AI_TRIAGE_FALLBACK_MODEL",
        "gabflow-triage-rules-v1",
    )
    AI_TRIAGE_PROMPT_VERSION = os.getenv("AI_TRIAGE_PROMPT_VERSION", "triage-v3")
    AI_TRIAGE_TIMEOUT_SECONDS = int(os.getenv("AI_TRIAGE_TIMEOUT_SECONDS", "120"))
    AI_TRIAGE_FALLBACK_ENABLED = os.getenv(
        "AI_TRIAGE_FALLBACK_ENABLED",
        "true",
    ).lower() == "true"
    AI_ASSISTANCE_PROVIDER = os.getenv("AI_ASSISTANCE_PROVIDER", AI_TRIAGE_PROVIDER)
    AI_ASSISTANCE_MODEL = os.getenv("AI_ASSISTANCE_MODEL", AI_TRIAGE_MODEL)
    AI_ASSISTANCE_FALLBACK_MODEL = os.getenv(
        "AI_ASSISTANCE_FALLBACK_MODEL", "gabflow-assistance-rules-v1"
    )
    AI_ASSISTANCE_PROMPT_VERSION = os.getenv(
        "AI_ASSISTANCE_PROMPT_VERSION", "assistance-v1"
    )
    AI_ASSISTANCE_TIMEOUT_SECONDS = int(
        os.getenv("AI_ASSISTANCE_TIMEOUT_SECONDS", str(AI_TRIAGE_TIMEOUT_SECONDS))
    )
    AI_ASSISTANCE_FALLBACK_ENABLED = os.getenv(
        "AI_ASSISTANCE_FALLBACK_ENABLED", "true"
    ).lower() == "true"
    AI_LEGISLATIVE_PROVIDER = os.getenv("AI_LEGISLATIVE_PROVIDER", AI_TRIAGE_PROVIDER)
    AI_LEGISLATIVE_MODEL = os.getenv("AI_LEGISLATIVE_MODEL", AI_TRIAGE_MODEL)
    AI_LEGISLATIVE_FALLBACK_MODEL = os.getenv(
        "AI_LEGISLATIVE_FALLBACK_MODEL", "gabflow-legislative-rules-v1"
    )
    AI_LEGISLATIVE_PROMPT_VERSION = os.getenv(
        "AI_LEGISLATIVE_PROMPT_VERSION", "legislative-v1"
    )
    AI_LEGISLATIVE_TIMEOUT_SECONDS = int(
        os.getenv("AI_LEGISLATIVE_TIMEOUT_SECONDS", str(AI_TRIAGE_TIMEOUT_SECONDS))
    )
    AI_LEGISLATIVE_FALLBACK_ENABLED = os.getenv(
        "AI_LEGISLATIVE_FALLBACK_ENABLED", "true"
    ).lower() == "true"
    AI_DUPLICATE_PROVIDER = os.getenv("AI_DUPLICATE_PROVIDER", "ollama")
    AI_EMBEDDING_MODEL = os.getenv("AI_EMBEDDING_MODEL", "nomic-embed-text")
    AI_DUPLICATE_WINDOW_DAYS = int(os.getenv("AI_DUPLICATE_WINDOW_DAYS", "180"))
    AI_DUPLICATE_SCORE_THRESHOLD = float(os.getenv("AI_DUPLICATE_SCORE_THRESHOLD", "0.72"))
    AI_DUPLICATE_MAX_SUGGESTIONS = int(os.getenv("AI_DUPLICATE_MAX_SUGGESTIONS", "5"))
    AI_DUPLICATE_CANDIDATE_LIMIT = int(os.getenv("AI_DUPLICATE_CANDIDATE_LIMIT", "100"))
    AI_PRECEDENT_PROVIDER = os.getenv("AI_PRECEDENT_PROVIDER", AI_DUPLICATE_PROVIDER)
    AI_PRECEDENT_SCORE_THRESHOLD = float(
        os.getenv("AI_PRECEDENT_SCORE_THRESHOLD", "0.60")
    )
    AI_PRECEDENT_MAX_RESULTS = int(os.getenv("AI_PRECEDENT_MAX_RESULTS", "10"))
    AI_PRECEDENT_CANDIDATE_LIMIT = int(
        os.getenv("AI_PRECEDENT_CANDIDATE_LIMIT", "200")
    )
    AI_FOUNDATION_PROVIDER = os.getenv("AI_FOUNDATION_PROVIDER", AI_PRECEDENT_PROVIDER)
    AI_FOUNDATION_SCORE_THRESHOLD = float(
        os.getenv("AI_FOUNDATION_SCORE_THRESHOLD", "0.55")
    )
    AI_FOUNDATION_MAX_RESULTS = int(os.getenv("AI_FOUNDATION_MAX_RESULTS", "5"))
    AI_FOUNDATION_CANDIDATE_LIMIT = int(
        os.getenv("AI_FOUNDATION_CANDIDATE_LIMIT", "200")
    )
    AUDIO_TRANSCRIPTION_PROVIDER = os.getenv(
        "AUDIO_TRANSCRIPTION_PROVIDER", "faster-whisper"
    )
    AUDIO_TRANSCRIPTION_MODEL = os.getenv("AUDIO_TRANSCRIPTION_MODEL", "base")
    AUDIO_TRANSCRIPTION_DEVICE = os.getenv("AUDIO_TRANSCRIPTION_DEVICE", "cpu")
    AUDIO_TRANSCRIPTION_COMPUTE_TYPE = os.getenv(
        "AUDIO_TRANSCRIPTION_COMPUTE_TYPE", "int8"
    )
    AUDIO_TRANSCRIPTION_LANGUAGE = os.getenv("AUDIO_TRANSCRIPTION_LANGUAGE", "pt")
    AUDIO_TRANSCRIPTION_CACHE_DIR = os.getenv(
        "AUDIO_TRANSCRIPTION_CACHE_DIR", "/models/whisper"
    )
    AUDIO_TRANSCRIPTION_MAX_DURATION_SECONDS = int(
        os.getenv("AUDIO_TRANSCRIPTION_MAX_DURATION_SECONDS", "900")
    )
    DOCUMENT_OCR_PROVIDER = os.getenv("DOCUMENT_OCR_PROVIDER", "tesseract")
    DOCUMENT_OCR_MODEL = os.getenv("DOCUMENT_OCR_MODEL", "tesseract-5")
    DOCUMENT_OCR_LANGUAGE = os.getenv("DOCUMENT_OCR_LANGUAGE", "por")
    DOCUMENT_OCR_MAX_PAGES = int(os.getenv("DOCUMENT_OCR_MAX_PAGES", "25"))
    DOCUMENT_OCR_MAX_PIXELS = int(os.getenv("DOCUMENT_OCR_MAX_PIXELS", "25000000"))
    OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://ollama:11434")


class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = "sqlite+pysqlite:///:memory:"
    JWT_COOKIE_SECURE = False
    RATELIMIT_ENABLED = False
    SENTRY_DSN = None
    RESEND_API_KEY = None
    RESEND_FROM_EMAIL = None
    AI_TRIAGE_PROVIDER = "local"
    AI_TRIAGE_MODEL = "gabflow-triage-rules-v1"
    AI_TRIAGE_FALLBACK_MODEL = "gabflow-triage-rules-v1"
    AI_TRIAGE_PROMPT_VERSION = "triage-v1"
    AI_ASSISTANCE_PROVIDER = "local"
    AI_ASSISTANCE_MODEL = "gabflow-assistance-rules-v1"
    AI_ASSISTANCE_FALLBACK_MODEL = "gabflow-assistance-rules-v1"
    AI_ASSISTANCE_PROMPT_VERSION = "assistance-v1"
    AI_LEGISLATIVE_PROVIDER = "local"
    AI_LEGISLATIVE_MODEL = "gabflow-legislative-rules-v1"
    AI_LEGISLATIVE_FALLBACK_MODEL = "gabflow-legislative-rules-v1"
    AI_LEGISLATIVE_PROMPT_VERSION = "legislative-v1"
    AI_DUPLICATE_PROVIDER = "local"
    AI_PRECEDENT_PROVIDER = "local"
    AI_PRECEDENT_SCORE_THRESHOLD = 0.2
    AI_FOUNDATION_PROVIDER = "local"
    AI_FOUNDATION_SCORE_THRESHOLD = 0.15
    RAG_EMBEDDING_PROVIDER = "local"
