"""response templates and scheduled returns

Revision ID: 14c336c05f68
Revises: ef1498b82cf5
Create Date: 2026-07-16 15:23:00.492624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '14c336c05f68'
down_revision = 'ef1498b82cf5'
branch_labels = None
depends_on = None


def upgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'RETORNO'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['request_categories.id'], name=op.f('fk_response_templates_category_id_request_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_response_templates_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_response_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_templates')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_response_templates_tenant_id'))
    )
    with op.batch_alter_table('response_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_templates_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_templates_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('scheduled_returns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AGENDADO', 'CONCLUIDO', 'CANCELADO', name='scheduled_return_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_scheduled_returns_assignee_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_scheduled_returns_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('fk_scheduled_returns_request_id_service_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scheduled_returns_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_returns'))
    )
    with op.batch_alter_table('scheduled_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_returns_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_returns_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_returns_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_returns_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_returns_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_returns_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_returns_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_returns_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_returns_request_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_returns_assignee_id'))

    op.drop_table('scheduled_returns')
    if op.get_bind().dialect.name == "postgresql":
        postgresql.ENUM(name="scheduled_return_status").drop(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('response_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_templates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_response_templates_channel'))
        batch_op.drop_index(batch_op.f('ix_response_templates_category_id'))

    op.drop_table('response_templates')
    # ### end Alembic commands ###
