"""add service requests

Revision ID: 288e894336ec
Revises: b628fb30e10d
Create Date: 2026-07-16 14:09:57.308858

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "288e894336ec"
down_revision = "b628fb30e10d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_outbox_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_outbox_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_outbox_events_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "service_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("protocol", sa.String(length=30), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "PRESENCIAL",
                "TELEFONE",
                "WHATSAPP",
                "EMAIL",
                "FORMULARIO",
                "REDE_SOCIAL",
                "VISITA",
                name="request_source",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=180), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOVA",
                "TRIAGEM",
                "EM_ATENDIMENTO",
                "AGUARDANDO_ORGAO",
                "AGUARDANDO_CIDADAO",
                "RESOLVIDA",
                "ENCERRADA",
                "CANCELADA",
                name="request_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("BAIXA", "MEDIA", "ALTA", "CRITICA", name="request_priority"),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("responsible_id", sa.Uuid(), nullable=True),
        sa.Column("duplicate_group_id", sa.Uuid(), nullable=True),
        sa.Column("closing_reason", sa.Text(), nullable=True),
        sa.Column("closing_evidence", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_service_requests_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responsible_id"],
            ["users.id"],
            name=op.f("fk_service_requests_responsible_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_service_requests_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_requests")),
        sa.UniqueConstraint("tenant_id", "protocol", name=op.f("uq_service_requests_tenant_id")),
    )
    with op.batch_alter_table("service_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_requests_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_duplicate_group_id"),
            ["duplicate_group_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_priority"), ["priority"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_responsible_id"), ["responsible_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_service_requests_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_service_requests_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "request_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_request_history_request_id_service_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_request_history_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_request_history_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_history")),
    )
    with op.batch_alter_table("request_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_request_history_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_request_history_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "request_interactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("interaction_type", sa.String(length=80), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("ENTRADA", "SAIDA", "INTERNA", name="interaction_direction"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("INTERNA", "CIDADAO", name="interaction_visibility"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_request_interactions_author_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_request_interactions_request_id_service_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_request_interactions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_interactions")),
    )
    with op.batch_alter_table("request_interactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_interactions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_request_interactions_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_request_interactions_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "protocol_sequence",
                sa.Integer(),
                server_default="0",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_column("protocol_sequence")

    with op.batch_alter_table("request_interactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_interactions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_request_interactions_request_id"))
        batch_op.drop_index(batch_op.f("ix_request_interactions_created_at"))

    op.drop_table("request_interactions")
    with op.batch_alter_table("request_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_history_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_request_history_request_id"))
        batch_op.drop_index(batch_op.f("ix_request_history_created_at"))

    op.drop_table("request_history")
    with op.batch_alter_table("service_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_requests_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_service_requests_status"))
        batch_op.drop_index(batch_op.f("ix_service_requests_responsible_id"))
        batch_op.drop_index(batch_op.f("ix_service_requests_priority"))
        batch_op.drop_index(batch_op.f("ix_service_requests_duplicate_group_id"))
        batch_op.drop_index(batch_op.f("ix_service_requests_created_at"))
        batch_op.drop_index(batch_op.f("ix_service_requests_category"))

    op.drop_table("service_requests")
    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_published_at"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_event_type"))

    op.drop_table("outbox_events")
    # ### end Alembic commands ###
