"""complete p1 office operations

Revision ID: 7f8f0bd60ade
Revises: aff877742382
Create Date: 2026-07-16 14:51:45.651423

"""

# ruff: noqa: E501

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f8f0bd60ade"
down_revision = "aff877742382"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_agencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("contact_email", sa.String(length=254), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_external_agencies_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_agencies")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_external_agencies_tenant_id")),
    )
    with op.batch_alter_table("external_agencies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_agencies_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "territories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_territories_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_territories")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_territories_tenant_id")),
    )
    with op.batch_alter_table("territories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_territories_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "request_forwardings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("external_protocol", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ENCAMINHADO",
                "AGUARDANDO_RETORNO",
                "RESPONDIDO",
                "ENCERRADO",
                name="forwarding_status",
            ),
            nullable=False,
        ),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["external_agencies.id"],
            name=op.f("fk_request_forwardings_agency_id_external_agencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_request_forwardings_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_request_forwardings_request_id_service_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_request_forwardings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_forwardings")),
    )
    with op.batch_alter_table("request_forwardings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_forwardings_agency_id"), ["agency_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_request_forwardings_due_at"), ["due_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_request_forwardings_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_request_forwardings_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_request_forwardings_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("service_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subcategory", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("theme", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("territory_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("agency_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("impact", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("urgency", sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column("public_access_key_hash", sa.String(length=64), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_agency_id"), ["agency_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_territory_id"), ["territory_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_service_requests_theme"), ["theme"], unique=False)
        batch_op.create_unique_constraint(
            batch_op.f("uq_service_requests_public_access_key_hash"), ["public_access_key_hash"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_service_requests_territory_id_territories"),
            "territories",
            ["territory_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_service_requests_agency_id_external_agencies"),
            "external_agencies",
            ["agency_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_requests", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_service_requests_agency_id_external_agencies"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_service_requests_territory_id_territories"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_service_requests_public_access_key_hash"), type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_service_requests_theme"))
        batch_op.drop_index(batch_op.f("ix_service_requests_territory_id"))
        batch_op.drop_index(batch_op.f("ix_service_requests_agency_id"))
        batch_op.drop_column("public_access_key_hash")
        batch_op.drop_column("urgency")
        batch_op.drop_column("impact")
        batch_op.drop_column("agency_id")
        batch_op.drop_column("territory_id")
        batch_op.drop_column("theme")
        batch_op.drop_column("subcategory")

    with op.batch_alter_table("request_forwardings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_forwardings_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_request_forwardings_status"))
        batch_op.drop_index(batch_op.f("ix_request_forwardings_request_id"))
        batch_op.drop_index(batch_op.f("ix_request_forwardings_due_at"))
        batch_op.drop_index(batch_op.f("ix_request_forwardings_agency_id"))

    op.drop_table("request_forwardings")
    with op.batch_alter_table("territories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_territories_tenant_id"))

    op.drop_table("territories")
    with op.batch_alter_table("external_agencies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_agencies_tenant_id"))

    op.drop_table("external_agencies")
    # ### end Alembic commands ###
