"""privacy rights retention and governance

Revision ID: 9e9623dd52f3
Revises: 14c336c05f68
Create Date: 2026-07-16 16:10:53.871614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9e9623dd52f3'
down_revision = '14c336c05f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('citizen_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('legal_basis', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_consent_records_citizen_id_citizens'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_consent_records_recorded_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consent_records_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_records'))
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('privacy_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('citizen_id', sa.Uuid(), nullable=False),
    sa.Column('request_type', sa.Enum('ACESSO', 'CORRECAO', 'ANONIMIZACAO', 'REVOGACAO_CONSENTIMENTO', name='privacy_request_type'), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANALISE', 'CONCLUIDA', 'REJEITADA', name='privacy_request_status'), nullable=False),
    sa.Column('identity_validated', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_privacy_requests_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_privacy_requests_citizen_id_citizens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_privacy_requests_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_privacy_requests_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_requests'))
    )
    with op.batch_alter_table('privacy_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privacy_requests_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_privacy_requests_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_privacy_requests_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_privacy_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_privacy_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_privacy_requests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('retention_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('REVISAR', 'ANONIMIZAR', name='retention_action'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_retention_policies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_retention_policies_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policies')),
    sa.UniqueConstraint('tenant_id', 'data_type', name=op.f('uq_retention_policies_tenant_id'))
    )
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_policies_tenant_id'), ['tenant_id'], unique=False)

    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            INSERT INTO consent_records (
                id, tenant_id, citizen_id, purpose, granted, legal_basis,
                source, recorded_by_id, recorded_at
            )
            SELECT gen_random_uuid(), c.tenant_id, c.id, purpose.name,
                   CASE purpose.name
                       WHEN 'CONTATO' THEN c.contact_consent
                       ELSE c.publication_consent
                   END,
                   c.legal_basis, 'MIGRACAO',
                   (
                       SELECT u.id FROM users u
                       WHERE u.tenant_id = c.tenant_id
                       ORDER BY u.created_at LIMIT 1
                   ),
                   c.created_at
            FROM citizens c
            CROSS JOIN (VALUES ('CONTATO'), ('DIVULGACAO')) AS purpose(name)
            WHERE EXISTS (
                SELECT 1 FROM users u WHERE u.tenant_id = c.tenant_id
            )
            """
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_policies_tenant_id'))

    op.drop_table('retention_policies')
    if op.get_bind().dialect.name == "postgresql":
        postgresql.ENUM(name="retention_action").drop(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('privacy_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privacy_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_privacy_requests_status'))
        batch_op.drop_index(batch_op.f('ix_privacy_requests_request_type'))
        batch_op.drop_index(batch_op.f('ix_privacy_requests_due_at'))
        batch_op.drop_index(batch_op.f('ix_privacy_requests_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_privacy_requests_assigned_to_id'))

    op.drop_table('privacy_requests')
    if op.get_bind().dialect.name == "postgresql":
        postgresql.ENUM(name="privacy_request_status").drop(op.get_bind(), checkfirst=True)
        postgresql.ENUM(name="privacy_request_type").drop(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_consent_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_consent_records_purpose'))
        batch_op.drop_index(batch_op.f('ix_consent_records_citizen_id'))

    op.drop_table('consent_records')
    # ### end Alembic commands ###
