"""complete p1 operations

Revision ID: aff877742382
Revises: 288e894336ec
Create Date: 2026-07-16 14:25:15.270900

"""

# ruff: noqa: E501

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aff877742382"
down_revision = "288e894336ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citizens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("social_name", sa.String(length=180), nullable=True),
        sa.Column("contacts", sa.JSON(), nullable=False),
        sa.Column("addresses", sa.JSON(), nullable=False),
        sa.Column("preferred_channel", sa.String(length=30), nullable=True),
        sa.Column("contact_consent", sa.Boolean(), nullable=False),
        sa.Column("publication_consent", sa.Boolean(), nullable=False),
        sa.Column("legal_basis", sa.String(length=120), nullable=False),
        sa.Column("privacy_flags", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_citizens_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citizens")),
    )
    with op.batch_alter_table("citizens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_citizens_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_citizens_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("organization_type", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("contacts", sa.JSON(), nullable=False),
        sa.Column("addresses", sa.JSON(), nullable=False),
        sa.Column("territory", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_organizations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_organizations_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "request_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sla_hours", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["request_categories.id"],
            name=op.f("fk_request_categories_parent_id_request_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_request_categories_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_categories")),
        sa.UniqueConstraint(
            "tenant_id", "name", "parent_id", name=op.f("uq_request_categories_tenant_id")
        ),
    )
    with op.batch_alter_table("request_categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_categories_parent_id"), ["parent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_request_categories_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "duplicate_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_duplicate_groups_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_duplicate_groups_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duplicate_groups")),
    )
    with op.batch_alter_table("duplicate_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_duplicate_groups_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum("ATRIBUICAO", "TAREFA", "SLA", "SISTEMA", name="notification_type"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_notifications_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_read_at"), ["read_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "scan_status",
            sa.Enum("PENDENTE", "LIMPO", "BLOQUEADO", name="attachment_scan_status"),
            nullable=False,
        ),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_attachments_request_id_service_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_attachments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_attachments_uploaded_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_attachments_storage_key")),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachments_request_id"), ["request_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachments_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachments_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "request_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDENTE", "EM_ANDAMENTO", "CONCLUIDA", "CANCELADA", name="task_status"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("BAIXA", "MEDIA", "ALTA", "CRITICA", name="task_priority"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_request_tasks_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_request_tasks_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_request_tasks_request_id_service_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_request_tasks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_tasks")),
    )
    with op.batch_alter_table("request_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_tasks_assignee_id"), ["assignee_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_request_tasks_due_at"), ["due_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_request_tasks_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_request_tasks_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_request_tasks_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("service_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("citizen_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("organization_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("due_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_service_requests_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_citizen_id"), ["citizen_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_service_requests_due_at"), ["due_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_service_requests_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_service_requests_citizen_id_citizens"),
            "citizens",
            ["citizen_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_service_requests_duplicate_group_id_duplicate_groups"),
            "duplicate_groups",
            ["duplicate_group_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_service_requests_category_id_request_categories"),
            "request_categories",
            ["category_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_service_requests_organization_id_organizations"),
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_requests", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_service_requests_organization_id_organizations"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_service_requests_category_id_request_categories"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_service_requests_duplicate_group_id_duplicate_groups"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_service_requests_citizen_id_citizens"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_service_requests_organization_id"))
        batch_op.drop_index(batch_op.f("ix_service_requests_due_at"))
        batch_op.drop_index(batch_op.f("ix_service_requests_citizen_id"))
        batch_op.drop_index(batch_op.f("ix_service_requests_category_id"))
        batch_op.drop_column("due_at")
        batch_op.drop_column("organization_id")
        batch_op.drop_column("citizen_id")
        batch_op.drop_column("category_id")

    with op.batch_alter_table("request_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_tasks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_request_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_request_tasks_request_id"))
        batch_op.drop_index(batch_op.f("ix_request_tasks_due_at"))
        batch_op.drop_index(batch_op.f("ix_request_tasks_assignee_id"))

    op.drop_table("request_tasks")
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_attachments_sha256"))
        batch_op.drop_index(batch_op.f("ix_attachments_request_id"))

    op.drop_table("attachments")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_read_at"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("duplicate_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_duplicate_groups_tenant_id"))

    op.drop_table("duplicate_groups")
    with op.batch_alter_table("request_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_categories_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_request_categories_parent_id"))

    op.drop_table("request_categories")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_organizations_name"))

    op.drop_table("organizations")
    with op.batch_alter_table("citizens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_citizens_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_citizens_name"))

    op.drop_table("citizens")
    # ### end Alembic commands ###
